name: Restful Booker API Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-html

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run API Tests
        run: |
          newman run ./Part_B_API_Automation/collection.json \
            -e ./Part_B_API_Automation/environment.json \
            -d data.json \
            -r cli,html \
            --reporter-html-export ./Part_B_API_Automation/reports/report.html

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/report.html